#!/bin/bash
# Generate and upload vim patch files

VIMCODE=${HOME}/code/vim

[[ -d ${VIMCODE} ]] || mkdir -p "${VIMCODE}"
pushd "${VIMCODE}" > /dev/null
hg pull -u

REV=$(hg tags | head -n 2 | tail -n1 | awk '{print $1}' | sed 's/v//')
MAJOR=$(echo ${REV} | cut -d- -f1)
MINOR=$(echo ${REV} | cut -d- -f2)
PATCH=$(echo ${REV} | cut -d- -f3 | sed 's/0*\(.\+\)/\1/')
VERSION=${MAJOR}.${MINOR}.${PATCH}

[[ -z ${VERSION} ]] && exit 1

hg diff -r "v${MAJOR}-${MINOR}" -r tip -X path:src/testdir * > vim-${VERSION}.patch
hg diff -a -r "v${MAJOR}-${MINOR}" -r tip -X path:./ -I path:src/testdir * >> vim-${VERSION}.patch
bzip2 vim-${VERSION}.patch

scp vim-${VERSION}.patch.bz2 dev.gentoo.org:public_html/vim/
rm vim-${VERSION}.patch.bz2

popd > /dev/null
