#!/bin/bash
# Generate and upload vim patch files

VIM_CODE=${HOME}/code/vim

[[ -d ${VIM_CODE} ]] || mkdir -p "${VIM_CODE}"
pushd "${VIM_CODE}" > /dev/null
hg pull -u

REV=$(hg tags | head -n 2 | tail -n1 | awk '{print $1}' | sed 's/v//')
MAJOR=$(echo ${REV} | cut -d- -f1)
MINOR=$(echo ${REV} | cut -d- -f2)
PATCH=$(echo ${REV} | cut -d- -f3 | sed 's/0*\(.\+\)/\1/')
VERSION=${MAJOR}.${MINOR}.${PATCH}

[[ -z ${VERSION} ]] && exit 1

VIM_PATCH=vim-${VERSION}.patch

hg diff -r "v${MAJOR}-${MINOR}" -r tip -X path:src/testdir * > ${VIM_PATCH}
hg diff -a -r "v${MAJOR}-${MINOR}" -r tip -X path:./ -I path:src/testdir * >> ${VIM_PATCH}
xz ${VIM_PATCH}

scp ${VIM_PATCH}.xz dev.gentoo.org:public_html/vim/
rm ${VIM_PATCH}.xz

popd > /dev/null
