#!/usr/bin/env python

import bz2
import errno
import gzip
import os
import re
import sys

from argparse import ArgumentParser
from tempfile import mkdtemp


def mkdir_p(path):
    try:
        os.makedirs(path)
    except OSError as exc:
        if exc.errno == errno.EEXIST:
            pass
        else:
            raise


class NoFilesFound(Exception):
    pass


class Vimball:
    def __init__(self, filepath, extractdir=None):
        self.filepath = filepath

        self.vimball = self._open_archive()

        if not self._is_vimball():
            raise TypeError

        if extractdir is None:
            extractdir = self.filepath
            if extractdir.endswith('.vba') or extractdir.endswith('.vmb'):
                extractdir = extractdir[:-4]
            if os.path.exists(extractdir):
                tempdir = mkdtemp(prefix='vimball-', dir=os.getcwd())
                extractdir = os.path.join(tempdir.split('/')[-1], extractdir)
        self.extractdir = extractdir

    def __del__(self):
        try:
            self.vimball.close()
        except AttributeError:
            return

    def _is_vimball(self):
        self.vimball.seek(0)
        header = self.vimball.readline()
        m = re.match('^" Vimball Archiver', header)

        if m is not None:
            return True
        else:
            return False

    def _open_archive(self):
        basename, extension = os.path.splitext(self.filepath)

        try:
            if extension == ".gz":
                f = gzip.open(self.filepath)
            elif extension == ".bz2":
                f = bz2.BZ2File(self.filepath)
            else:
                f = open(self.filepath)
        except IOError:
            print("That file doesn't exist!")
            sys.exit(errno.ENOENT)

        return f

    def _find_files(self, header):
        filename = None
        self.vimball.seek(0)
        line = self.vimball.readline()
        while line:
            m = header.match(line)
            if m is not None:
                filename = m.group(1)
                filelines = int(self.vimball.readline().rstrip())
                filestart = self.vimball.tell()
                yield (filename, filelines, filestart)
            line = self.vimball.readline()

        if filename is None:
            raise NoFilesFound

    def files(self):
        header = re.compile(r"(.*)\t\[\[\[1\n")
        try:
            return self._find_files(header)
        except NoFilesFound:
            header = re.compile(r"^(\d+)\n$")
            try:
                return self._find_files(header)
            except NoFilesFound:
                raise SystemExit('No files were found in vimball: {}'.format(self.filepath))

    def list(self):
        for (filename, lines, offset) in self.files():
            print(filename)

    def extract(self):
        self.vimball.seek(0)

        for (filename, lines, offset) in self.files():
            filepath = os.path.join(self.extractdir, filename)
            mkdir_p(os.path.dirname(filepath))
            f = open(filepath, 'w')
            print(filepath)
            self.vimball.seek(offset)
            for i in range(lines):
                f.write(self.vimball.readline())
            f.close

if __name__ == "__main__":
    parser = ArgumentParser(description='Vimball (un)archiver', prog='vimball')

    parser.add_argument('archive', nargs=1)
    parser.add_argument('-x', '--extract', help='extract files from a vimball archive',
        action='store_true', dest='extract')
    parser.add_argument('-l', '--list', help='list files a vimball archive',
        action='store_true', dest='list')
    parser.add_argument('-C', '--directory', help='extract files to a specified directory',
        metavar='DIR', dest='extractdir')

    args = parser.parse_args()

    vimball = Vimball(args.archive[0], args.extractdir)

    if args.extract:
       vimball.extract()
    elif args.list:
       vimball.list()

# vim:et:
